name: Flutter CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build Split APKs
        run: flutter build apk --split-per-abi

      - name: Build Android App Bundle (AAB)
        run: flutter build appbundle

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: split-apks
          path: build/app/outputs/flutter-apk/*-release.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-bundle
          path: build/app/outputs/bundle/release/app-release.aab
