name: Flutter CI

on:
  workflow_dispatch:
    inputs:
      build_apk:
        description: 'Build Split APKs'
        required: true
        type: boolean
        default: true
      build_aab:
        description: 'Build AAB (App Bundle)'
        required: true
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build Split APKs
        if: ${{ inputs.build_apk == true }}
        run: flutter build apk --split-per-abi

      - name: Build Android App Bundle (AAB)
        if: ${{ inputs.build_aab == true }}
        run: flutter build appbundle

      - name: Upload APKs
        if: ${{ inputs.build_apk == true }}
        uses: actions/upload-artifact@v4
        with:
          name: split-apks
          path: build/app/outputs/flutter-apk/*-release.apk

      - name: Upload AAB
        if: ${{ inputs.build_aab == true }}
        uses: actions/upload-artifact@v4
        with:
          name: app-bundle
          path: build/app/outputs/bundle/release/app-release.aab
